#version: '3.1'
#services:
#  springboot-rabbitmq:
#    image: rabbitmq:3-management
#    ports:
#      - '5672:5672'
#      - '15672:15672'
#    environment:
#      - RABBITMQ_DEFAULT_USER=user
#      - RABBITMQ_DEFAULT_PASSWORD=user
#docker run -d --hostname my-rabbit --name some-rabbit -p 15672:15672 -p 5672:5672 rabbitmq:3-management